name: Spectators
version: 1.0
main: us.meyerzinn.bukkit.Spectators.Spectators
author: 20zinnm
commands:
  spectate:
    description: Turn spectate mode on/off.
    usage: Use /<command> to toggle spectator mode.
    permission: spectators.spectate
    permission-message: Insufficient Permissions!